# NORMALIZATION PROBLEM

In [8]:
import numpy as np

X = np.random.rand(5, 5)

mean = X.mean()
std = X.std()

X_normalized = (X - mean) / std

np.save("X_normalized.npy", X_normalized)

print("Original Array (X):\n", X)
print("\nMean:", mean)
print("Standard Deviation:", std)
print("\nNormalized Array (X_normalized):\n", X_normalized)

Original Array (X):
 [[0.94621708 0.17849886 0.90645998 0.61271652 0.82153426]
 [0.62985671 0.56693455 0.82244617 0.36914241 0.94123483]
 [0.06790169 0.2596271  0.52459722 0.8019553  0.31717034]
 [0.18681462 0.6450093  0.61977529 0.90374272 0.27556631]
 [0.98684195 0.73998256 0.16184843 0.88021299 0.43002871]]

Mean: 0.5838446355836373
Standard Deviation: 0.28426012596867334

Normalized Array (X_normalized):
 [[ 1.2747917  -1.42596777  1.13492999  0.10156853  0.83616941]
 [ 0.16186609 -0.05948807  0.83937743 -0.75530196  1.25726459]
 [-1.81503805 -1.14056636 -0.20842676  0.76729252 -0.93813472]
 [-1.39671372  0.21517144  0.12640062  1.12537094 -1.08449373]
 [ 1.41770611  0.54927833 -1.48454239  1.0425956  -0.54110974]]


# DIVISIBLE BY 3 PROBLEM

In [10]:
import numpy as np

squares = np.arange(1, 101) ** 2

A = squares.reshape(10, 10)

div_by_3 = A[A % 3 == 0]

np.save("div_by_3.npy", div_by_3)

print("10x10 ndarray of squares: \n", A)
print("\nElements divisible by 3:\n", div_by_3)

10x10 ndarray of squares: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
